---
- name: "Install Podman"
  hosts: centos
  become: yes
  vars:
    package_name: 
      - name: podman
#      - name: containers-tools
#      - name: podman-docker

  tasks:
    - name: Install podman package 
      ansible.builtin.yum:
        name: "{{ item.name }}"
        enablerepo: extras
        state: present
      loop: "{{ package_name }}"