---
- name: "Restaure existing volume volume.tar"
  hosts: centos
  become: true
  become_user: kafka

  tasks:

  - name: Copy volume podman restaure script
    ansible.builtin.copy:
      src: ../files/v_podman_restaure.sh
      dest: /tmp/ 
      mode: 0755

  # - name: Stop Container if running

  - name: List  Existing Volume 
    become: true
    become_user: root
    ansible.builtin.shell:
      cmd: docker volume ls --format '{{' {{print .Name}} '}}'
    register: results

  - debug: var=results.stdout_lines

  - name: Import Existing Volume 
    ansible.builtin.shell:
      cmd: /tmp/v_podman_restaure.sh import "{{ item }}".tar "{{ item }}"
      chdir: /tmp
    loop: "{{ results.stdout_lines }}"